module.exports.keywords = /gaffe|ancient|star-studded|remains to be seen|silver bullet|subway system|surprising|war of words|tension|cautiously optimistic|doctor who|win votes|behind the headlines|email|facebook post|tweet|facebook ceo|\bdisrupt\b|meeting|scientists|you won't believe|debate|self driving|poll|candidate|drone|vows to|at large|successfully|expands|first-degree|second-degree|third-degree|an unknown number|front runner|global|years|minutes|no indication|urged restraint by|horsepower|witnesses|allegedly|new study|rebuild|space|google glass|smartphone|electric|senator|\bcar\b|election|congressional leaders|homeland security|could not be reached for comment/gi;

module.exports.substitutionsObj = {
	witnesses: "these dudes I know",
	allegedly: "kinda probably",
	'new study': "tumblr post",
	rebuild: "avenge",
	space: "spaaace",
	'google glass': "virtual boy",
	smartphone: "pokedex", 
	electric: "atomic",
	senator: "elf-lord",
	car: "cat",
	election: "eating contest",
	'congressional leaders': "river spirits",
	'homeland security': "homestar runner", 
	'could not be reached for comment': "is guilty and everyone knows it",
	debate: "dance-off",
	'self driving': "uncontrollably swerving",
	poll: "psychic reading",
	candidate: "airbender",
	drone: "dog",
	'vows to': "probably won't",
	'at large': "very large",
	successfully: "suddenly",
	expands: "physically expands",
	'first-degree': "friggin' awful",
	'second-degree': "friggin' awful",
	'third-degree': "friggin' awful",
	'an unknown number': "like hundreds",
	'front runner': "blade runner",
	'global': "spherical",
	years: "minutes",
	minutes: "years",
	'no indication': "lots of signs",
	'urged restraint by': "drunkenly egged on",
	'horsepower': "tons of horsemeat",
	gaffe: "magic spell", 
	ancient: "haunted",
	'star-studded': "blook-soaked",
	'remains to be seen': "will never be knowned",
	'silver bullet': "way to kill werewolves",
	'subway system': "tunnels I found",
	'surprising': "surprising (but not to me)",
	'war of words': "interplanetary war",
	'tension': "sexual tension",
	'cautiously optimistic': "delusional",
	'doctor who': "The Big Bang Theory", 
	'win votes': "find pokemon",
	'behind the headlines': "beyond the grave",
	'email': "poem",
	'facebook post': "poem",
	'tweet': "poem",
	'facebook ceo': "this guy",
	'disrupt': "destroy",
	'meeting': "ménage à trois",
	'scientists': "Channing Tatum and his friends",
	"you won't believe": "I'm really sad about"
};